name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0  # Specify the .NET SDK version

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Build the project
    - name: Build Project
      run: dotnet build --no-restore --configuration Release

    # Run tests
    - name: Run Unit Tests
      run: dotnet test --no-build --configuration Release --verbosity normal

    # Publish build artifacts
    - name: Publish Artifacts
      run: dotnet publish -c Release -o ./publish
