name: Build, Test, and Deploy ASP.Net Core App to Azure Web App - animalracing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.428'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the application
        run: dotnet build --configuration Release

      # Upload build artifact for test job
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: . # Upload the entire repository for testing

  test:
    runs-on: windows-latest
    needs: build

    steps:
      # Download the build artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # Run tests
      - name: Run Unit Tests
        run: dotnet test --configuration Release --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
      # Download the artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'animalracing'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
